-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 14:50:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hishob
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hishob
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hishob` DEFAULT CHARACTER SET utf8 ;
USE `hishob` ;

-- -----------------------------------------------------
-- Table `hishob`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hishob`.`bank` (
  `uuid` VARCHAR(40) NULL DEFAULT NULL,
  `bank_id` INT(11) NOT NULL,
  `bank_name` VARCHAR(50) NULL DEFAULT NULL,
  `created` VARCHAR(20) NULL DEFAULT NULL,
  `modified` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`bank_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hishob`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hishob`.`user` (
  `uuid` VARCHAR(40) NULL DEFAULT NULL,
  `user_id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `middle_name` VARCHAR(50) NULL DEFAULT NULL,
  `user_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mobile_number` BIGINT(8) NULL DEFAULT NULL,
  `passsword` VARCHAR(40) NULL DEFAULT NULL,
  `created` VARCHAR(20) NULL DEFAULT NULL,
  `modified` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hishob`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hishob`.`bank_account` (
  `uuid` VARCHAR(40) NULL DEFAULT NULL,
  `bank_account_id` BIGINT(8) NOT NULL,
  `account_number` VARCHAR(50) NULL DEFAULT NULL,
  `account_type` VARCHAR(50) NULL DEFAULT NULL,
  `user_id` BIGINT(8) NOT NULL,
  `bank_id` INT(11) NULL DEFAULT NULL,
  `created` VARCHAR(20) NULL DEFAULT NULL,
  `modified` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`bank_account_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `bank_id_idx` (`bank_id` ASC),
  CONSTRAINT `bank_id`
    FOREIGN KEY (`bank_id`)
    REFERENCES `hishob`.`bank` (`bank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `hishob`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hishob`.`cash_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hishob`.`cash_account` (
  `uuid` VARCHAR(40) NULL DEFAULT NULL,
  `cash_account_id` BIGINT(8) NOT NULL,
  `user_id` BIGINT(8) NULL DEFAULT NULL,
  `created` VARCHAR(20) NULL DEFAULT NULL,
  `modified` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`cash_account_id`),
  INDEX `user_id_cash_account` (`user_id` ASC),
  CONSTRAINT `user_id_cash_account`
    FOREIGN KEY (`user_id`)
    REFERENCES `hishob`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hishob`.`debit_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hishob`.`debit_credit` (
  `uuid` VARCHAR(40) NULL DEFAULT NULL,
  `expense_id` BIGINT(8) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `credited` TINYINT(4) NULL DEFAULT NULL,
  `bank_account_id` BIGINT(8) NULL DEFAULT NULL,
  `cash_account_id` BIGINT(8) NULL DEFAULT NULL,
  `category` VARCHAR(20) NULL DEFAULT NULL,
  `created` VARCHAR(20) NULL DEFAULT NULL,
  `modified` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`expense_id`),
  INDEX `bank_account_id_idx` (`bank_account_id` ASC),
  INDEX `cash_account_id_idx` (`cash_account_id` ASC),
  CONSTRAINT `bank_account_id`
    FOREIGN KEY (`bank_account_id`)
    REFERENCES `hishob`.`bank_account` (`bank_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cash_account_id`
    FOREIGN KEY (`cash_account_id`)
    REFERENCES `hishob`.`cash_account` (`cash_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
